
  CREATE TABLE STADIUM
   (	STADIUM_ID NUMBER, 
	STADIUM_NAME VARCHAR2(30), 
	STADIUM_CITY VARCHAR2(30), 
	MATCHES_COUNTS NUMBER, 
	C_ID NUMBER,
	CONSTRAINT C_ID_FK FOREIGN KEY (C_ID) REFERENCES COUNTRY(C_ID)
   ) 
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (1,'M. Chinnaswamy ','Bangalore',81,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (2,'PCA ','Mohali',49,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (3,'Feroz Shah Kotla Ground','Delhi',67,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (4,'Eden Gardens','Kolkata',70,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (5,'Wankhede ','Mumbai',66,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (6,'Sawai Mansingh ','Jaipur',40,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (7,'Rajiv Gandhi International  ','Hyderabad',56,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (8,'M. A. Chidambaram ','Chennai',49,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (9,'DY Patil ','Navi Mumbai',17,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (10,'Brabourne ','Mumbai',11,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (11,'Barabati ','Cuttack',7,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (12,'Sardar Patel ','Ahmedabad',12,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (13,'VCA ','Nagpur',3,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (14,'HPCA ','Dharamshala',9,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (15,'Jawaharlal Nehru ','Kochi',5,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (16,'Holkar ','Indore',9,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (17,'ACA-VDCA ','Visakhapatnam',11,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (18,'Maharashtra  Association ','Pune',38,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (19,'Raipur International  ','Raipur',6,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (20,'JSCA International  ','Ranchi',7,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (21,'Saurashtra  Association ','Rajkot',10,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (22,'Green Park ','Kanpur',4,1);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (23,'Newlands  Ground','Cape Town',7,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (24,'St George''s Oval','Port Elizabeth',7,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (25,'Kingsmead  Ground','Durban',15,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (26,'SuperSport Park','Centurion',12,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (27,'Buffalo Park','East London',3,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (28,'New Wanderers ','Johannesburg',8,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (29,'De Beers Diamond Oval','Kimberley',3,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (30,'Chevrolet Park','Bloemfontein',2,2);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (31,'Sheikh Zayed  ','Abu Dhabi',7,3);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (32,'Sharjah  ','Sharjah',6,3);
Insert into STADIUM (STADIUM_ID,STADIUM_NAME,STADIUM_CITY,MATCHES_COUNTS,C_ID) values (33,'Dubai International  ','Dubai',7,3);
