CREATE TABLE Umpires(
   Umpire_ID    INTEGER  NOT NULL PRIMARY KEY 
  ,Umpire_Name  VARCHAR(25) NOT NULL
  ,Nationality  VARCHAR(12) NOT NULL
  ,Total_Matches INTEGER  NOT NULL
);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (1,'Sundaram Ravi','India',109);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (2,'Kumar Dharmasena','South Africa',94);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (3,'Anil Chaudhary','India',78);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (4,'Chettithody shamshuddin','India',74);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (5,'Marais Erasmus','South Africa',66);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (6,'Simon Taufel','Australia',55);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (7,'Asad rauf','Pakistan',51);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (8,'C. K. Nandan','India',55);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (9,'Billy Doctrove','West Indies',44);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (10,'Vineet Kulkarni','India',48);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (11,'Rudi Koertzen','South Africa',42);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (12,'Rod Tucker','Australia',46);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (13,'Billy Bowden','New Zealand',38);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (14,'Aleem Dar','Pakistan',38);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (15,'Bruce Oxenford','Australia',48);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (16,'Nitin Menon','India',43);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (17,'Sudhir Asnani','India',31);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (18,'Shavir Tarapore','India',31);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (19,'Nigel Llong','England',37);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (20,'Russell Tiffin','Zimbabwe',30);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (21,'Chris Gaffaney','New Zealand',33);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (22,'Daryl Harper','Australia',28);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (23,'Amiesh Saheba','India',27);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (24,'Krishna Hariharan','India',21);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (25,'Nand Kishor','India',21);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (26,'Richard Illingworth','England',20);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (27,'K. N. Ananthapadmanabhan','India',18);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (28,'Brian Jerling','South Africa',18);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (29,'Johan Cloete','South Africa',17);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (30,'Anil Dandekar','India',17);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (31,'Sanjay Hazare','India',17);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (32,'Virender Sharma','India',16);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (33,'Subrat Das','India',15);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (34,'Krishnaraj Srinath','India',15);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (35,'Ian Howell','South Africa',14);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (36,'Suresh Shastri','India',14);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (37,'Mark Benson','England',13);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (38,'Abhijit Deshmukh','India',12);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (39,'Paul Reiffel','Australia',11);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (40,'Yeshwant Barde','India',9);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (41,'Rajesh Deshpande','India',8);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (42,'Pashchim Pathak','India',8);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (43,'Gary Baxter','New Zealand',7);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (44,'Steve Davis','Australia',7);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (45,'Arani Jayprakash','India',7);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (46,'Simon Fry','Australia',6);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (47,'Tony Hill','New Zealand',6);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (48,'G. A. Pratapkumar','India',6);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (49,'Ivaturi Shivram','India',6);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (50,'Tyron Wijewardene','Sri Lanka',6);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (51,'Krishnamachari Bharatan','India',3);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (52,'Krishnamachari Srinivasan','India',3);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (53,'Ulhas Gandhe','India',2);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (54,'Shashank Ranade','India',2);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (55,'Subroto Das','India',1);
INSERT INTO Umpires(Umpire_ID,Umpire_Name,Nationality,Total_Matches) VALUES (56,'Ian Gould','England',1);
